name: Branch Based CI/CD

on:
  push:
jobs:

  build:
    name: Build Stage main
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Build for PROD
        if: github.ref_name == 'main'
        run: |
          echo "=============================="
          echo "🚀 BUILD STAGE - PRODUCTION"
          echo "Branch: ${{ github.ref_name }}"
          echo "=============================="
  deploy:
    name: Deploy Stage main
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Deploy for PROD
        if: github.ref_name == 'main'
        run: |
          echo "=============================="
          echo "🚀 DEPLOY STAGE - PRODUCTION"
          echo "Branch: ${{ github.ref_name }}"
          echo "=============================="
