name: Branch Based CI/CD

on:
  push:
    branches:
      - dev
jobs:

  build:
    name: Build Stage dev
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Build for DEV
        run: |
          echo "=============================="
          echo "🚀 BUILD STAGE - DEV"
          echo "Branch: ${{ github.ref_name }}"
          echo "=============================="
  deploy:
    name: Deploy Stage DEV
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Deploy for DEV
        run: |
          echo "=============================="
          echo "🚀 DEPLOY STAGE - DEV"
          echo "Branch: ${{ github.ref_name }}"
          echo "=============================="
